executable = /afs/cern.ch/user/s/schuetha/work/private/GNN/FCGNN/evaluates.sh
epoch=150
model=FCGNN/SNDShowerClassifier_Full_FC.yaml
out_path=SNDShowerClassifier_Full_FC_new_300cut
name=SNDShowerClassifier_Full_FC_new_300cut
max_job=16
batch_size=128
arguments = $(epoch) $(model) $(out_path) $(max_job) $(batch_size)
log = /afs/cern.ch/user/s/schuetha/work/private/GNN/train_GNN_$(epoch)_$(name).log
error = /afs/cern.ch/user/s/schuetha/work/private/GNN/train_GNN_$(epoch)_$(name).error
output = /afs/cern.ch/user/s/schuetha/work/private/GNN/train_GNN_$(epoch)_$(name).out
request_gpus    = 1
should_transfer_files = YES
request_CPUs = 1
request_memory  = 32 GB
+AccountingGroup = "group_u_SNDLHC.users"
+JobFlavour = "nextweek"
queue 1