executable = /afs/cern.ch/user/s/schuetha/work/private/GNN/FCGNN/GNN_flavour_oh_ori.sh
log = /afs/cern.ch/user/s/schuetha/work/private/GNN/Data_converted_loader_flavour.log
error = /afs/cern.ch/user/s/schuetha/work/private/GNN/Data_converted_loader_flavour.error
output = /afs/cern.ch/user/s/schuetha/work/private/GNN/Data_converted_loader_flavour.out
should_transfer_files = YES
request_CPUs = 5
request_memory  = 48 GB
+AccountingGroup = "group_u_SNDLHC.users"
+JobFlavour = "nextweek"
queue 1